# Generated by Django 4.0.2 on 2022-02-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('Second_name', models.CharField(max_length=150, verbose_name='Second Name')),
                ('email', models.CharField(max_length=150, verbose_name='email')),
                ('mobile', models.IntegerField(max_length=300, verbose_name='Mobile')),
                ('Message', models.TextField(max_length=500, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'ContacUs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'ImageAdd',
                'ordering': ['id'],
            },
        ),
    ]
