# Generated by Django 4.0.2 on 2022-02-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacus',
            name='mobile',
            field=models.IntegerField(verbose_name='Mobile'),
        ),
    ]
